# Generated by Django 3.2.7 on 2021-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hability', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-first_name'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Mi Personal'},
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('first_name', 'last_name')},
        ),
    ]
