# Generated by Django 3.2.7 on 2021-09-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210912_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='habilities',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
