# Generated by Django 3.2.7 on 2021-09-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_curriculum_vitae'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apodo generado automaticamente'),
        ),
    ]
